---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv1
  namespace: sean-koval
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data1"
