---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: sean-koval
  labels:
    app: redis
    tier: backend
spec:
  #clusterIP: None # maybe change type to clusterIP
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    tier: backend
