---
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

namespace: sean-koval
bases:
  - ../../bases
  - ./namespace.yaml
patches:
  - path: patch-deployment-mlapi.yaml
    target:
      kind: Deployment
